name: safetyZone
description: "safetyZone is a mobile application designed to enhance personal
  safety and security. It provides users with features such as emergency
  contacts, location sharing, and real-time alerts to ensure their well-being in
  various situations."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  bloc: ^9.0.0
  connectivity_plus: ^6.1.1
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_local_notifications: ^19.1.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  fluttertoast: ^8.2.8
  freezed_annotation: ^3.0.0
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  get_it: ^8.0.3
  go_router: ^15.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.5.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  pin_code_fields: ^8.0.1
  pinput: ^5.0.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.0.1
  shared_preferences: ^2.5.2
  google_fonts: ^6.1.0
  url_launcher: ^6.3.1
  flutter_spinkit:
  table_calendar:
  pdf: ^3.10.4
  printing: ^5.11.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  retrofit_generator: ^9.2.0


dependency_overrides:
  intl: ^0.20.1

flutter:
  uses-material-design: true
  assets:
    - assets/.
    - assets/lang/.
    - assets/logos/.
    - assets/icons/.
    - assets/images/
    - assets/fonts/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 800
